server:
  port: 8082
spring:
  application:
    name: registry
eureka:
  instance:
    hostname: eureka2  #Eureka服务端的实例名称
    instance-id: registry-8082
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:8081/eureka/ #http://${eureka.instance.hostname}:${server.port}/eureka/,

