spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=true&setTimezone=GMT
    username: root
    password: weijianfeng666
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10
      max-wait: 3000
      min-idle: 3
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: eureka-service-8011 #服务名不可用下划线连接
mybatis:
  type-aliases-package: cn.wjf.spring.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: INFO
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8081/eureka/,http://eureka2:8082/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
#    hostname: localhost  #必须要有，dashboard不识别公网ip对应的域名，只能识别本地host文件包含的域名
    prefer-ip-address: true #是否展示ip地址
    instance-id: service-8011
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]
